Add Lisa's entry for 21.01.2022
alasco-tech/alasco-inside.github.io pull request #2
Opened 2022-01-21 17:53 UTC by glsignal

2022-01-24 08:01 UTC, sixfwa requested changes
Thank you so much for add this :). Ive just added one change in regarding the files. However there is one more in the `index.html`. There is an area with the heading titled "Latest Blogposts". Could you please add in this blog post there :) 

Thanks again

2022-01-24 08:01 UTC, sixfwa commented on blog/lisa-event-marketing-manager.html
> +    <meta content="Sophia as a UI/UX Designer" property="twitter:description">
Would change the meta tags to fit with the blog ;)

2022-01-24 08:23 UTC, glsignal commented on blog/lisa-event-marketing-manager.html
> +    <meta content="Sophia as a UI/UX Designer" property="twitter:description">
Thanks good catch! Updated the notes too, and also added one for the breadcrumb link

2022-01-24 10:19 UTC, sixfwa commented on blog/lisa-event-marketing-manager.html
> +    <meta content="Sophia as a UI/UX Designer" property="twitter:description">
awesome thank you :)

2022-01-27 13:23 UTC, sixfwa approved these changes
🚀 🚀 let's get this literature deployed

2022-01-27 13:24 UTC, merged

2022-01-27 13:24 UTC, glsignal commented
Prose: released